# Generated by Django 4.2.7 on 2026-06-16 11:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('median_income', models.FloatField()),
                ('house_age', models.FloatField()),
                ('avg_rooms', models.FloatField()),
                ('avg_bedrooms', models.FloatField()),
                ('population', models.FloatField()),
                ('avg_occupancy', models.FloatField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('predicted_price', models.FloatField()),
                ('predicted_price_usd', models.FloatField()),
                ('confidence_level', models.CharField(max_length=50)),
                ('model_used', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prediction Record',
                'verbose_name_plural': 'Prediction Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
